# Generated by Django 4.1.4 on 2023-05-16 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sname',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
