# Generated by Django 4.1.4 on 2023-05-16 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_school_sname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sid',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
